spring:
  application:
    name: service-discovery

server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    definitions-service: /definitions/**
    rnd-service: /rnd/**

